workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_KEYSTORE: mykey.jks # <-- Put your encrypted keystore here
        FCI_KEYSTORE_PASSWORD: mykeys # <-- Put your encrypted keystore password here
        FCI_KEY_PASSWORD: mykeys # <-- Put your encrypted key alias password here
        FCI_KEY_ALIAS: mykey # <-- Put your encrypted key alias here
        PACKAGE_NAME: "kalgi.com.i_am_rich1" # <-- Put your package name here
    scripts:
      scripts:
  - name: Build Android
    script: |
      echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
      cd android && ./gradlew assembleRelease
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

      email:
        recipients:
          - kalgi@nevercode.io
         
        notify:
          success: true     # To not receive a notification when a build succeeds
          failure: false    # To not receive a notification when a build fails
      
